### ISSUE TITLE
Counter-clockwise rotation of the model

### ISSUE THREAD

**Issue by Viccsasa** [Holo-Repository/Unity3D-ModelViewer#8]
It seems that the counter-clockwise rotation doesn't work correct because of the spelling issue. The case name in Rotation90 is 'cClock' but was called with 'cclock'

**Comment by ThiagoBour** [comment]
Fixed on branch "HR-84-Fix-Model-Fetcher-for-WebGL-Deployment", will be merged into main shortly.
